import type { Metadata } from "next";
import "./globals.css";
import { SWRConfig } from "swr";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`bg-gray-100`}>
        <SWRConfig value={{ dedupingInterval: 10000, revalidateOnFocus: false }}>{children}</SWRConfig>
      </body>
    </html>
  );
}
